font_family  Caskaydiacove Nerd Font Mono
font_size 14

disable_ligatures no
enable_audio_bell no

shell             zsh
shell_integration disabled

cursor_shape block

url_style curly

remember_window_size no

window_padding_width 20

background_opacity 0.8

scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

sync_to_monitor no


#some colors

background #090200
foreground #a4a1a1
cursor #a4a1a1
selection_background #494542
color0 #090200
color8 #5b5754
color1 #da2c20
color9 #e8bacf
color2 #00a152
color10 #3a3332
color3 #fcec02
color11 #494542
color4 #00a0e4
color12 #7f7c7b
color5 #a06994
color13 #d6d4d3
color6 #b5e4f4
color14 #ccab53
color7 #a4a1a1
color15 #f7f7f7
selection_foreground #090200
