source = ~/.config/hypr/configs/settings.conf
source = ~/.config/hypr/configs/variables.conf
source = ~/.config/hypr/configs/keybind.conf
source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/window_rule.conf
source = ~/.config/hypr/configs/animation.conf

