source = /home/arihant/.cache/wal/colors-hyprland.conf
monitor = ,preferred,auto,1
dwindle {
	pseudotile = true
	preserve_split = true
}

master {
	new_on_top = 1
	mfact = 0.70
}

general {
	border_size = 1
	gaps_in = 5
	gaps_out = 5
	resize_on_border = true
	layout = dwindle

	col.active_border = $color1 
	col.inactive_border = $color8
}


group {
  	col.border_active = $color1   # blood red (focus indicator)

  	groupbar {
    		col.active = $color4        # moonlight beige
  }
}

decoration {
	rounding = 17
	active_opacity = 0.95
	inactive_opacity = 0.85
	fullscreen_opacity = 1.0

	dim_inactive = true
	dim_strength = 0.10

	shadow {
		enabled = true
		range = 16
		render_power = 2
		offset = 2 2
		color = rgba(20,16,16,0.65)

	}
	blur {
    		enabled = true
    		size = 8
    		passes = 2
    		new_optimizations = true
    		ignore_opacity = false
  	}
}

input {
	kb_layout = us
	kb_model = 
	kb_variant = 
	kb_options = 
	kb_rules = 

	repeat_rate = 35
	repeat_delay = 250
	sensitivity = 0

	scroll_method = 2fg
	natural_scroll = false
	follow_mouse = 1
	float_switch_override_focus = 0

	touchpad {
  		disable_while_typing = false
		natural_scroll = true
  		clickfinger_behavior = false
          	middle_button_emulation = true
  		tap-to-click = true
  		drag_lock = false
	}
	
}

gesture = 3, horizontal, workspace

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	vrr = 2 
	enable_swallow = true 
	swallow_regex = ^(kitty)$
	focus_on_activate = false

}

binds {
	workspace_back_and_forth = true
	allow_workspace_cycles = true

}

xwayland {
	force_zero_scaling = true
}

render {
	direct_scanout = 2
}
